language: node_js
node_js:
- "8.9.1"
cache:
	yarn: true
  directories:
  - "node_modules"
before_install:
  - npm i -g npm@version-number
	- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
	- export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  - git diff --exit-code # make sure that yarn.lock didn't change
script:
#	- yarn runt lint

	