language: node_js

# test on two node.js versions: 0.6 and 0.8
node_js:
  - 0.6
  - 0.8

# https://yarnpkg.com/lang/en/docs/install-ci/
sudo: required
before_install: # if "install" is overridden
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn

# https://blog.travis-ci.com/2016-11-21-travis-ci-now-supports-yarn
cache:
  yarn: true
  directories:
    - node_modules

env:
  global:
    - YARN_VERSION='1.3.2'

notifications:
  slack:
    on_success: never
    on_failure: always

install:
  - . $HOME/.nvm/nvm.sh; nvm install stable; nvm use stable
	- yarn

script:
  - node --version
