language: node_js
node_js: "8"

cache:
  - yarn

env:
  global:
    - YARN_VERSION='0.24.5'

notifications:
  slack:
    on_success: never
    on_failure: always

install:
  - . $HOME/.nvm/nvm.sh; nvm install stable; nvm use stable
  - ./bin/ci/install-yarn
  - yarn

script:
  - node --version